const LENGTH_COMMENT = 140;

const COUNT_HASHTAGS = 5;
const MIN_HASHTAG_LENGTH = 2;
const MAX_HASHTAG_LENGTH = 20;

const COUNT_COMMENTS_PER_PAGE = 5;

const SCALE_PHOTO_MIN = 25;
const SCALE_PHOTO_MAX = 100;
const SCALE_PHOTO_CHANGE = 25;

const ALERT_SHOW_TIME = 10000;

const NUMBER_RANDOM_PHOTOS = 10;

export {
  LENGTH_COMMENT,
  COUNT_HASHTAGS,
  MAX_HASHTAG_LENGTH,
  MIN_HASHTAG_LENGTH,
  COUNT_COMMENTS_PER_PAGE,
  SCALE_PHOTO_MIN,
  SCALE_PHOTO_MAX,
  SCALE_PHOTO_CHANGE,
  ALERT_SHOW_TIME,
  NUMBER_RANDOM_PHOTOS
};
