const LENGTH_COMMENT = 140;

const COUNT_HASHTAGS = 5;
const MIN_HASHTAG_LENGTH = 2;
const MAX_HASHTAG_LENGTH = 20;

const COUNT_COMMENTS_PER_PAGE = 5;

const SCALE_PHOTO_MIN = 25;
const SCALE_PHOTO_MAX = 100;
const SCALE_PHOTO_CHANGE = 25;
const START_VALUE_SCALE = '100%';
const COEFFICIENT_STYLE_TRANSFORM_SCALE = 0.01;

const ALERT_SHOW_TIME = 10000;
const RERENDER_DELAY_FILTERS = 500;

const NUMBER_RANDOM_PHOTOS = 10;

const FILE_TYPES = ['gif', 'jpg', 'jpeg', 'png'];

export {
  LENGTH_COMMENT,
  COUNT_HASHTAGS,
  MAX_HASHTAG_LENGTH,
  MIN_HASHTAG_LENGTH,
  COUNT_COMMENTS_PER_PAGE,
  SCALE_PHOTO_MIN,
  SCALE_PHOTO_MAX,
  SCALE_PHOTO_CHANGE,
  START_VALUE_SCALE,
  COEFFICIENT_STYLE_TRANSFORM_SCALE,
  ALERT_SHOW_TIME,
  RERENDER_DELAY_FILTERS,
  NUMBER_RANDOM_PHOTOS,
  FILE_TYPES
};
