const LENGTH_COMMENT = 140;
const COUNT_HASHTAGS = 5;
const MIN_HASHTAG_LENGTH = 2;
const MAX_HASHTAG_LENGTH = 20;
const COUNT_COMMENTS_PER_PAGE = 5;

export {
  LENGTH_COMMENT,
  COUNT_HASHTAGS,
  MAX_HASHTAG_LENGTH,
  MIN_HASHTAG_LENGTH,
  COUNT_COMMENTS_PER_PAGE
};
